### ISSUE TITLE
Unable to build v2.3 locally

### ISSUE THREAD

**Issue by DPUkyle** [gradle/gradle-enterprise-build-validation-scripts#358]
I saw the recent release of `v2.3` and tried to build locally, using the following steps:

1. `$ git pull`
2. `$ git checkout v2.3`
3. `$ ./gradlew clean -is # uses Gradle 8.0.2 wrapper, results in error`

The following ST occurs:

```
FAILURE: Build failed with an exception.

* What went wrong:
The Gradle Enterprise server address 'https://us-build-cache.gradle.org/cache/' value should not contain a path component

* Try:
> Run with --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: The Gradle Enterprise server address 'https://us-build-cache.gradle.org/cache/' value should not contain a path component
        at com.gradle.scan.agent.a.b.c.a(SourceFile:63)
        at com.gradle.scan.agent.a.b.c.a(SourceFile:54)
        at com.gradle.enterprise.gradleplugin.GradleEnterpriseBuildCache.setServer(SourceFile:82)
        at com.gradle.enterprise.gradleplugin.internal.a.b_Decorated.setServer(Unknown Source)
        at com.gradle.Overrides.lambda$configureBuildCache$6(Overrides.java:76)
        at org.gradle.caching.configuration.internal.DefaultBuildCacheConfiguration.remote(DefaultBuildCacheConfiguration.java:101)
        at com.gradle.Overrides.configureBuildCache(Overrides.java:75)
        at com.gradle.CommonCustomUserDataGradlePlugin.lambda$applySettingsPlugin$0(CommonCustomUserDataGradlePlugin.java:76)
```

It seems there may be an incompatibility with `CommonCustomUserDataGradlePlugin` and Gradle 8.x?

**Comment by DPUkyle** [comment]
Update: the following patch is a workaround allowing me to make some progress:

```
diff --git a/settings.gradle.kts b/settings.gradle.kts
index 486cfd0..974600b 100644
--- a/settings.gradle.kts
+++ b/settings.gradle.kts
@@ -2,7 +2,7 @@ import com.gradle.enterprise.gradleplugin.internal.extension.BuildScanExtensionW
 
 plugins {
     id("com.gradle.enterprise") version "3.12.4"
-    id("com.gradle.common-custom-user-data-gradle-plugin") version "1.9"
+    //id("com.gradle.common-custom-user-data-gradle-plugin") version "1.9"
 }
 
 val isCI = System.getenv("GITHUB_ACTIONS") != null
```

**Comment by DPUkyle** [comment]
I now have the following issue: https://e.grdev.net/s/5ppcz2jndmieg

```
> Task :generateBashCliParsers FAILED
/Users/kmoore/dev/gradle/gradle-enterprise-build-validation-scripts/build/argbash/bin/argbash: line 371: syntax error near unexpected token `<'
/Users/kmoore/dev/gradle/gradle-enterprise-build-validation-scripts/build/argbash/bin/argbash: line 371: `      done < <(echo 'm4_changecom()m4_define([ARGBASH_WRAP])' "$(cat "$1")" \'

```

**Comment by DPUkyle** [comment]
The root cause of the `com.gradle.common-custom-user-data-gradle-plugin` incompatibility is this sysprop defined in `~./gradle/gradle.properties`:

```
systemProp.gradle.cache.remote.url=https://us-build-cache.gradle.org/cache/
```

Commenting-out or removing this line allows the build to be configured.  However there is still an issue with the `:generateBashCliParsers` task.

**Comment by erichaagdev** [comment]
Thank you, @DPUkyle! I am closing this issue as it has been determined to not be an issue with the Gradle Enterprise build validation scripts.

**Comment by etiennestuder** [comment]
> After [gradle/common-custom-user-data-gradle-plugin#141](https://github.com/gradle/common-custom-user-data-gradle-plugin/issues/141) is fixed, CCUD plugin should be bumped in this repo.

@DPUkyle Yes, we always update to the latest CCUD plugin version as part of our version upgrade process.

**Comment by DPUkyle** [comment]
Fixed by #609
