### ISSUE TITLE
Unable to connect to server to fetch build scan

### ISSUE THREAD

**Issue by ritesh-singh** [gradle/gradle-enterprise-build-validation-scripts#488]
While, it works well for experiment-01 - shows valid `Performance Characteristics` summary.

```
Fetching Build Scan data for all builds
ERROR: Unable to connect to server to fetch build scan
```
But, it fails from experiment-02 and onwards with above error. Just the `Performance Characteristics` is affected. Script is able to publish scan data to Gradle enterprise server.
 
 Project is connect with gradle enterprise. I am using v2.5 script!
 
 Below commands was uses for invoking experiment-02 on CI.
 
 ./02-validate-local-build-caching-same-location.sh -r file:///__w/my-project/my-project -t :target:assembleDebug -s https://myGe.example.com/

**Comment by ritesh-singh** [comment]
I ran the script, with --debug flag
`./02-validate-local-build-caching-same-location.sh --debug -r file://$GITHUB_WORKSPACE -t $TASKS -s $GRADLE_ENTERPRISE_URL`

Looks like it's timing out! Authentication issue seems to be ruled out.

Fetching Build Scan data for all builds
Using anonymous authentication.
Using anonymous authentication.
```
com.gradle.enterprise.api.client.FailedRequestException: Unable to connect to server to fetch build scan https://https://myge.example.com/s/z3mfjmjmncfta
	at com.gradle.enterprise.api.client.GradleEnterpriseApiClient.fetchBuildScanData(GradleEnterpriseApiClient.java:177)
	at com.gradle.enterprise.cli.FetchBuildScanDataCommand.fetchBuildScanData(FetchBuildScanDataCommand.java:91)
	at com.gradle.enterprise.cli.FetchBuildScanDataCommand.lambda$fetchBuildScanData$1(FetchBuildScanDataCommand.java:83)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.gradle.enterprise.cli.FetchBuildScanDataCommand.fetchBuildScanData(FetchBuildScanDataCommand.java:84)
	at com.gradle.enterprise.cli.FetchBuildScanDataCommand.call(FetchBuildScanDataCommand.java:69)
	at com.gradle.enterprise.cli.FetchBuildScanDataCommand.call(FetchBuildScanDataCommand.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.gradle.enterprise.Main.main(Main.java:15)
Caused by: com.gradle.enterprise.api.client.ApiException: Message: java.net.SocketTimeoutException: timeout
HTTP response code: 0
HTTP response body: null
HTTP response headers: null
	at com.gradle.enterprise.api.client.ApiClient.execute(ApiClient.java:1046)
	at com.gradle.enterprise.api.GradleEnterpriseApi.getBuildWithHttpInfo(GradleEnterpriseApi.java:346)
	at com.gradle.enterprise.api.GradleEnterpriseApi.getBuild(GradleEnterpriseApi.java:322)
	at com.gradle.enterprise.api.client.GradleEnterpriseApiClient.fetchBuildScanData(GradleEnterpriseApiClient.java:133)
	... 27 more
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:97)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.gradle.enterprise.api.client.ApiClient$2.intercept(ApiClient.java:1453)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.gradle.enterprise.api.client.ApiClient.execute(ApiClient.java:1042)
	... 30 more
```

**Comment by erichaagdev** [comment]
Hi @ritesh-singh! Thanks for reaching out. Here are a few things to check.

Make sure your Gradle Enterprise server is reachable from the machine you are running the build validation scripts from. If you run the build like normal, are you getting a build scan?

Next, in your most recent message I see this as the server URL as `https://https://myge.example.com/s/z3mfjmjmncfta`. I'm going to assume that was a mistake when attempting to obfuscate the hostname. Please double check this.

Next, please ensure proper authentication to the server. On your Gradle Enterprise server, go to `/settings/permissions` and verify that you have `Access build data via the API` checked. Then verify you have a valid API access key at `~/.gradle/enterprise/keys.properties` or `~/.m2/.gradle-enterprise/keys.properties`. If one does not exist, please [generate an access key](https://docs.gradle.com/enterprise/gradle-plugin/#authenticating).

Finally, the build validation scripts will only wait up to 10 seconds for the build scans to become available. This means the summary of the build validation scripts may not have the data for the performance characteristics section if the server is under load and ingest is slow. This is also expected functionality. You can still use the investigation quick links to assess the experiment outcome. If you believe this to be the case, please contact us via https://support.gradle.com and [include a support bundle](https://docs.gradle.com/enterprise/helm-admin/current/#support) so that we may verify your installation.

**Comment by ritesh-singh** [comment]
Thanks @erichaagdev 

> Next, in your most recent message I see this as the server URL as https://https://myge.example.com/s/z3mfjmjmncfta. I'm going to assume that was a mistake when attempting to obfuscate the hostname. Please double check this.

Yeah, server url is correct. Sorry for the confusion.

> Make sure your Gradle Enterprise server is reachable from the machine you are running the build validation scripts from. If you run the build like normal, are you getting a build scan?

Yeah, enterprise server is reachable.

> Next, please ensure proper authentication to the server. On your Gradle Enterprise server

I believe proper authentication is in place - few runs were able to fetch the scan data and add it in the summary.

> go to /settings/permissions and verify that you have Access build data via the API checked. 

Checked

> Then verify you have a valid API access key at ~/.gradle/enterprise/keys.properties or ~/.m2/.gradle-enterprise/keys.properties. If one does not exist, please [generate an access key](https://docs.gradle.com/enterprise/gradle-plugin/#authenticating)

I believe authentication must be happening using the gradle enterprise username and password added in our settings.gradle file. I did try the access key approach as well. I ran into the same issue.


> Finally, the build validation scripts will only wait up to 10 seconds for the build scans to become available. This means the summary of the build validation scripts may not have the data for the performance characteristics section if the server is under load and ingest is slow. This is also expected functionality

Yeah, looks like the could be the case. I was able to see Performance Characteristics details in some runs. That indicates authentication and other settings isn't a problem.


> You can still use the investigation quick links to assess the experiment outcome

💯 

> If you believe this to be the case, please contact us via https://support.gradle.com/ and [include a support bundle](https://docs.gradle.com/enterprise/helm-admin/current/#support) so that we may verify your installation.

Thanks, I will open a ticket with support bundle.

**Comment by erichaagdev** [comment]
> Thanks, I will open a ticket with support bundle.

Perfect. Since we verified the problem is with slow ingests I will close this issue.

Thanks again for reaching out.
